# Generated by Django 2.2.5 on 2019-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ext_color', models.CharField(max_length=50)),
                ('int_color', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
