# Generated by Django 2.2.5 on 2019-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
